### ISSUE TITLE
Getting the HEAD of the Git tree failed

### ISSUE THREAD

**Issue by VKNemsara** [sherubthakur/dotfiles#11]
Hey Sharub,

I just tried running nix run home-manager --no-write-lock-file -- switch --flake "./#nixos" but it gives an error

`error: getting the HEAD of the Git tree '/home/kavija/.dotfiles' failed with exit code 1:`
           `error: executing 'git' : No such file or directory`

I'm new to NixOS. Is there a way to fix this ?

**Comment by sherubthakur** [comment]
Unrelated to the dotfiles. It looks like you don't have git or something.
