### ISSUE TITLE
error: attribute should have type "derivation"

### ISSUE THREAD

**Issue by mike2505** [sherubthakur/dotfiles#5]
Hi, i am new to Nix, how can i fix this?
![IMG_20220602_194938](https://user-images.githubusercontent.com/37780087/171670236-1169ddf5-dd56-44c7-9cf1-83748111dadd.jpg)

**Comment by sherubthakur** [comment]
These are mostly personal dotfiles, so I doubt I will find the time to look into issues related to these.
